### PR TITLE
I've incorporated your changes, and added some.

### PR DESCRIPTION
**Pull request by kescherCode**
Thank you so much for doing the implementation for playlists, albums and shows.
Here's some additional changes by me:

- Preserve order of tracks and episodes in playlists, albums and shows
- Reverse the order of episode ids in a show
- End stdin loop if line matches "done"
- Prevent crash on invalid input

### CODE REVIEW

**Comment by elganzua124** [comment]
Cool, you're welcome. Thanks for letting me know, and for improving my code. I'm really new to Rust. Now I am thinking of adding the functionality of insert the cover art in each track.

**Comment by kescherCode** [comment]
I'm thinking that the existing `tag_ogg` script could have an added argument for a temporary file path for a cover image, and the cover itself is already retrievable via librespot as well. (Although the program should recover gracefully if no cover is found).

**Comment by elganzua124** [comment]
Actually, adding a cover to an ogg file it's kinda complex. A script that truly works is this: https://github.com/acabal/scripts/blob/master/ogg-cover-art
So the `tag_ogg` script could call that script, or make a function inside.

**Comment by kescherCode** [comment]
I haven't looked at the script, but I imagine it embeds it in a VorbisComment, as usual for Xiph.Org formats.

**Pull request merged**
